export interface TeamInfo {
  abbreviation: string
  teamCity: string
  teamName: string
  conference: 'Eastern' | 'Western'
  division: string
  logoUrl: string
  firstSeason: string
  lastSeason: string
}

function seasonStart(season: string): number {
  return parseInt(season.split('-')[0], 10)
}

export function isTeamInSeason(team: TeamInfo, season: string): boolean {
  const s = seasonStart(season)
  return s >= seasonStart(team.firstSeason) && s <= seasonStart(team.lastSeason)
}

export function getTeamsForSeason(season: string): TeamInfo[] {
  return TEAM_INFO.filter((t) => isTeamInSeason(t, season))
}

export const TEAM_INFO: TeamInfo[] = [
  {
    abbreviation: 'KCK',
    teamCity: 'Kansas City',
    teamName: 'Kings',
    conference: 'Western',
    division: 'Midwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612758/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '1984-85',
  },
  {
    abbreviation: 'SDC',
    teamCity: 'San Diego',
    teamName: 'Clippers',
    conference: 'Western',
    division: 'Pacific',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612746/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '1983-84',
  },
  {
    abbreviation: 'WSB',
    teamCity: 'Washington',
    teamName: 'Bullets',
    conference: 'Eastern',
    division: 'Atlantic',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612764/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '1996-97',
  },
  {
    abbreviation: 'ATL',
    teamCity: 'Atlanta',
    teamName: 'Hawks',
    conference: 'Eastern',
    division: 'Southeast',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612737/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2025-26',
  },
  {
    abbreviation: 'BOS',
    teamCity: 'Boston',
    teamName: 'Celtics',
    conference: 'Eastern',
    division: 'Atlantic',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612738/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2025-26',
  },
  {
    abbreviation: 'CHI',
    teamCity: 'Chicago',
    teamName: 'Bulls',
    conference: 'Eastern',
    division: 'Central',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612741/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2024-25',
  },
  {
    abbreviation: 'CLE',
    teamCity: 'Cleveland',
    teamName: 'Cavaliers',
    conference: 'Eastern',
    division: 'Central',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612739/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2025-26',
  },
  {
    abbreviation: 'DAL',
    teamCity: 'Dallas',
    teamName: 'Mavericks',
    conference: 'Western',
    division: 'Southwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612742/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'DEN',
    teamCity: 'Denver',
    teamName: 'Nuggets',
    conference: 'Western',
    division: 'Northwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612743/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'DET',
    teamCity: 'Detroit',
    teamName: 'Pistons',
    conference: 'Eastern',
    division: 'Central',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612765/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2025-26',
  },
  {
    abbreviation: 'GSW',
    teamCity: 'Golden State',
    teamName: 'Warriors',
    conference: 'Western',
    division: 'Pacific',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612744/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'HOU',
    teamCity: 'Houston',
    teamName: 'Rockets',
    conference: 'Western',
    division: 'Southwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612745/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'IND',
    teamCity: 'Indiana',
    teamName: 'Pacers',
    conference: 'Eastern',
    division: 'Central',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612754/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2024-25',
  },
  {
    abbreviation: 'LAL',
    teamCity: 'Los Angeles',
    teamName: 'Lakers',
    conference: 'Western',
    division: 'Pacific',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612747/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'MIL',
    teamCity: 'Milwaukee',
    teamName: 'Bucks',
    conference: 'Eastern',
    division: 'Central',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612749/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2024-25',
  },
  {
    abbreviation: 'NJN',
    teamCity: 'New Jersey',
    teamName: 'Nets',
    conference: 'Eastern',
    division: 'Atlantic',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612751/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2011-12',
  },
  {
    abbreviation: 'NYK',
    teamCity: 'New York',
    teamName: 'Knicks',
    conference: 'Eastern',
    division: 'Atlantic',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612752/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2025-26',
  },
  {
    abbreviation: 'PHI',
    teamCity: 'Philadelphia',
    teamName: '76ers',
    conference: 'Eastern',
    division: 'Atlantic',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612755/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'PHO',
    teamCity: 'Phoenix',
    teamName: 'Suns',
    conference: 'Western',
    division: 'Pacific',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612756/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'POR',
    teamCity: 'Portland',
    teamName: 'Trail Blazers',
    conference: 'Western',
    division: 'Northwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612757/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'SAS',
    teamCity: 'San Antonio',
    teamName: 'Spurs',
    conference: 'Western',
    division: 'Southwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612759/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'SEA',
    teamCity: 'Seattle',
    teamName: 'Supersonics',
    conference: 'Western',
    division: 'Pacific',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612760/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2007-08',
  },
  {
    abbreviation: 'UTA',
    teamCity: 'Utah',
    teamName: 'Jazz',
    conference: 'Western',
    division: 'Northwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612762/global/L/logo.svg',
    firstSeason: '1983-84',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'LAC',
    teamCity: 'LA',
    teamName: 'Clippers',
    conference: 'Western',
    division: 'Pacific',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612746/global/L/logo.svg',
    firstSeason: '1984-85',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'SAC',
    teamCity: 'Sacramento',
    teamName: 'Kings',
    conference: 'Western',
    division: 'Pacific',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612758/global/L/logo.svg',
    firstSeason: '1985-86',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'CHH',
    teamCity: 'Charlotte',
    teamName: 'Hornets',
    conference: 'Eastern',
    division: 'Central',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612766/global/L/logo.svg',
    firstSeason: '1988-89',
    lastSeason: '2001-02',
  },
  {
    abbreviation: 'MIA',
    teamCity: 'Miami',
    teamName: 'Heat',
    conference: 'Eastern',
    division: 'Southeast',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612748/global/L/logo.svg',
    firstSeason: '1988-89',
    lastSeason: '2024-25',
  },
  {
    abbreviation: 'MIN',
    teamCity: 'Minnesota',
    teamName: 'Timberwolves',
    conference: 'Western',
    division: 'Northwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612750/global/L/logo.svg',
    firstSeason: '1989-90',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'ORL',
    teamCity: 'Orlando',
    teamName: 'Magic',
    conference: 'Eastern',
    division: 'Southeast',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612753/global/L/logo.svg',
    firstSeason: '1989-90',
    lastSeason: '2024-25',
  },
  {
    abbreviation: 'TOR',
    teamCity: 'Toronto',
    teamName: 'Raptors',
    conference: 'Eastern',
    division: 'Atlantic',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612761/global/L/logo.svg',
    firstSeason: '1995-96',
    lastSeason: '2025-26',
  },
  {
    abbreviation: 'VAN',
    teamCity: 'Vancouver',
    teamName: 'Grizzlies',
    conference: 'Western',
    division: 'Midwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612763/global/L/logo.svg',
    firstSeason: '1995-96',
    lastSeason: '2000-01',
  },
  {
    abbreviation: 'WAS',
    teamCity: 'Washington',
    teamName: 'Wizards',
    conference: 'Eastern',
    division: 'Southeast',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612764/global/L/logo.svg',
    firstSeason: '1997-98',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'MEM',
    teamCity: 'Memphis',
    teamName: 'Grizzlies',
    conference: 'Western',
    division: 'Southwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612763/global/L/logo.svg',
    firstSeason: '2001-02',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'NOH',
    teamCity: 'New Orleans',
    teamName: 'Hornets',
    conference: 'Western',
    division: 'Southwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612740/global/L/logo.svg',
    firstSeason: '2002-03',
    lastSeason: '2012-13',
  },
  {
    abbreviation: 'CHA',
    teamCity: 'Charlotte',
    teamName: 'Bobcats',
    conference: 'Eastern',
    division: 'Southeast',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612766/global/L/logo.svg',
    firstSeason: '2004-05',
    lastSeason: '2013-14',
  },
  {
    abbreviation: 'NOK',
    teamCity: 'New Orleans',
    teamName: 'Hornets',
    conference: 'Western',
    division: 'Southwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612740/global/L/logo.svg',
    firstSeason: '2005-06',
    lastSeason: '2006-07',
  },
  {
    abbreviation: 'OKC',
    teamCity: 'Oklahoma City',
    teamName: 'Thunder',
    conference: 'Western',
    division: 'Northwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612760/global/L/logo.svg',
    firstSeason: '2008-09',
    lastSeason: '2024-25',
  },
  {
    abbreviation: 'BRK',
    teamCity: 'Brooklyn',
    teamName: 'Nets',
    conference: 'Eastern',
    division: 'Atlantic',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612751/global/L/logo.svg',
    firstSeason: '2012-13',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'NOP',
    teamCity: 'New Orleans',
    teamName: 'Pelicans',
    conference: 'Western',
    division: 'Southwest',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612740/global/L/logo.svg',
    firstSeason: '2013-14',
    lastSeason: '2023-24',
  },
  {
    abbreviation: 'CHO',
    teamCity: 'Charlotte',
    teamName: 'Hornets',
    conference: 'Eastern',
    division: 'Southeast',
    logoUrl: 'https://cdn.nba.com/logos/nba/1610612766/global/L/logo.svg',
    firstSeason: '2014-15',
    lastSeason: '2023-24',
  },
]

export const TEAM_BY_ABBREVIATION = Object.fromEntries(
  TEAM_INFO.map((team) => [team.abbreviation, team] as const)
) as Record<string, TeamInfo>

export const NBA_TEAMS = TEAM_INFO.map((team) => ({
  name: `${team.teamCity} ${team.teamName}`,
  conference: team.conference,
  division: team.division,
}))

export const TEAM_LOGOS = Object.fromEntries(
  TEAM_INFO.map((team) => [
    `${team.teamCity} ${team.teamName}`,
    team.logoUrl,
  ] as const)
) as Record<string, string>
